# Site settings
title: Lacuna Edge
email: lacunaedge@gmail.com
url: https://lacunaedge.github.io
description: "Experts in engineering, design and data analysis."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Lacuna Edge

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Email
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: github
    url: https://github.com/lacunaedge

# Build settings
markdown: kramdown
permalink: pretty
